In [1]:
import pandas as pd

In [5]:
df=pd.read_json("../data/final_dataset.json")
df.head(20)

,Url,BathroomCount,BedroomCount,ConstructionYear,Country,District,Fireplace,FloodingZone,Furnished,Garden,...,RoomCount,ShowerCount,StateOfBuilding,SubtypeOfProperty,SurfaceOfPlot,SwimmingPool,Terrace,ToiletCount,TypeOfProperty,TypeOfSale
2,https://www.immoweb.be/en/classified/apartment...,1.0,1,1969.0,Belgium,Brugge,NaN,None,NaN,NaN,...,1.0,0.0,GOOD,flat_studio,NaN,NaN,1.0,1.0,2,residential_sale
6,https://www.immoweb.be/en/classified/house/for...,6.0,13,1920.0,Belgium,Tournai,NaN,None,0.0,NaN,...,31.0,NaN,GOOD,apartment_block,130.0,NaN,NaN,5.0,1,residential_sale
8,https://www.immoweb.be/en/classified/house/for...,2.0,4,2008.0,Belgium,Brugge,NaN,NON_FLOOD_ZONE,1.0,NaN,...,NaN,0.0,GOOD,house,0.0,NaN,NaN,2.0,1,residential_sale
10,https://www.immoweb.be/en/classified/house/for...,1.0,4,NaN,Belgium,Veurne,NaN,None,NaN,1.0,...,NaN,NaN,TO_BE_DONE_UP,house,170.0,0.0,1.0,2.0,1,residential_sale
11,https://www.immoweb.be/en/classified/apartment...,0.0,2,1972.0,Belgium,Hasselt,NaN,NON_FLOOD_ZONE,NaN,NaN,...,1.0,0.0,AS_NEW,apartment,NaN,NaN,1.0,1.0,2,residential_sale
14,https://www.immoweb.be/en/classified/apartment...,1.0,1,1994.0,Belgium,Brussels,NaN,None,1.0,NaN,...,NaN,NaN,AS_NEW,apartment,NaN,0.0,1.0,1.0,2,residential_sale
15,https://www.immoweb.be/en/classified/house/for...,4.0,6,1970.0,Belgium,Nivelles,1.0,NON_FLOOD_ZONE,NaN,1.0,...,NaN,0.0,GOOD,villa,2519.0,NaN,1.0,5.0,1,residential_monthly_rent
18,https://www.immoweb.be/en/classified/house/for...,0.0,2,NaN,Belgium,Mechelen,NaN,NON_FLOOD_ZONE,NaN,NaN,...,1.0,0.0,None,house,423.0,NaN,NaN,0.0,1,residential_sale
22,https://www.immoweb.be/en/classified/apartment...,2.0,3,2023.0,Belgium,Halle-Vilvoorde,NaN,None,NaN,NaN,...,NaN,0.0,None,apartment,NaN,0.0,NaN,NaN,2,residential_sale
23,https://www.immoweb.be/en/classified/apartment...,NaN,2,NaN,Belgium,Sint-Niklaas,NaN,None,NaN,NaN,...,NaN,0.0,None,apartment,NaN,NaN,NaN,NaN,2,residential_sale
24,https://www.immoweb.be/en/classified/apartment...,1.0,2,1961.0,Belgium,Oostend,NaN,None,1.0,NaN,...,NaN,0.0,GOOD,apartment,NaN,NaN,NaN,1.0,2,residential_sale
25,https://www.immoweb.be/en/classified/apartment...,1.0,3,NaN,Belgium,Brussels,NaN,NON_FLOOD_ZONE,NaN,NaN,...,6.0,2.0,GOOD,apartment,NaN,0.0,1.0,3.0,2,residential_monthly_rent
27,https://www.immoweb.be/en/classified/house/for...,3.0,5,1987.0,Belgium,Antwerp,NaN,NON_FLOOD_ZONE,NaN,NaN,...,NaN,0.0,None,house,5185.0,NaN,NaN,3.0,1,residential_sale
29,https://www.immoweb.be/en/classified/apartment...,NaN,1,NaN,Belgium,Sint-Niklaas,NaN,None,NaN,NaN,...,NaN,0.0,None,apartment,NaN,NaN,NaN,NaN,2,residential_sale
30,https://www.immoweb.be/en/classified/apartment...,1.0,2,1966.0,Belgium,Oostend,NaN,NON_FLOOD_ZONE,1.0,NaN,...,NaN,NaN,None,apartment,NaN,0.0,NaN,NaN,2,residential_sale
33,https://www.immoweb.be/en/classified/house/for...,1.0,8,1923.0,Belgium,Ieper,NaN,NON_FLOOD_ZONE,NaN,1.0,...,16.0,NaN,TO_RENOVATE,house,223.0,0.0,1.0,2.0,1,residential_sale
34,https://www.immoweb.be/en/classified/house/for...,1.0,3,NaN,Belgium,Mons,NaN,None,NaN,NaN,...,NaN,0.0,TO_RESTORE,house,480.0,NaN,NaN,2.0,1,residential_sale
35,https://www.immoweb.be/en/classified/apartment...,1.0,0,1974.0,Belgium,Namur,NaN,NON_FLOOD_ZONE,NaN,NaN,...,NaN,1.0,GOOD,flat_studio,NaN,0.0,1.0,1.0,2,residential_sale
36,https://www.immoweb.be/en/classified/apartment...,1.0,0,1974.0,Belgium,Namur,NaN,NON_FLOOD_ZONE,0.0,NaN,...,NaN,NaN,GOOD,flat_studio,NaN,0.0,1.0,NaN,2,residential_sale
37,https://www.immoweb.be/en/classified/house/for...,0.0,1,1860.0,Belgium,Philippeville,NaN,NON_FLOOD_ZONE,NaN,NaN,...,NaN,NaN,TO_RENOVATE,house,189.0,0.0,1.0,NaN,1,residential_sale

In [4]:
df["TypeOfSale"].unique()

array([ 1.,  2., nan])

In [3]:
df["TypeOfSale"]=df.TypeOfSale.apply(lambda x : 1 if "residential_sale" in x else (2 if "monthly_rent" in x else None))

In [8]:
df.dropna(subset=["TypeOfSale"],inplace=True)
df.shape

(118399, 32)

In [9]:
print(df.columns.values)
df.info()

['Url' 'BathroomCount' 'BedroomCount' 'ConstructionYear' 'Country'
 'District' 'Fireplace' 'FloodingZone' 'Furnished' 'Garden' 'GardenArea'
 'Kitchen' 'LivingArea' 'Locality' 'MonthlyCharges' 'NumberOfFacades'
 'PEB' 'PostalCode' 'Price' 'PropertyId' 'Province' 'Region' 'RoomCount'
 'ShowerCount' 'StateOfBuilding' 'SubtypeOfProperty' 'SurfaceOfPlot'
 'SwimmingPool' 'Terrace' 'ToiletCount' 'TypeOfProperty' 'TypeOfSale']
<class 'pandas.core.frame.DataFrame'>
Index: 118399 entries, 2 to 181792
Data columns (total 32 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Url                118399 non-null  object
 1   BathroomCount      108827 non-null  float64
 2   BedroomCount       118399 non-null  int64
 3   ConstructionYear   68683 non-null   float64
 4   Country            118399 non-null  object
 5   District           118392 non-null  object
 6   Fireplace          4083 non-null    float64
 7   FloodingZone       58215 non-null   object
 8   Furnished          30268 non-null   float64
 9   Garden             22435 non-null   float64
 10  GardenArea         22435 non-null   float64
 11  Kitchen            66871 non-null   object
 12  LivingArea         104271 non-null  float64
 13  Locality           118397 non-null  object
 14  MonthlyCharges     13451 non-null   float64
 15  NumberOfFacades    76665 non-null   float64
 16  PEB                84832 non-null   object
 17  PostalCode         118399 non-null  int64
 18  Price              118399 non-null  int64
 19  PropertyId         118399 non-null  int64
 20  Province           118392 non-null  object
 21  Region             118392 non-null  object
 22  RoomCount          32894 non-null   float64
 23  ShowerCount        56882 non-null   float64
 24  StateOfBuilding    81419 non-null   object
 25  SubtypeOfProperty  118399 non-null  object
 26  SurfaceOfPlot      58038 non-null   float64
 27  SwimmingPool       40294 non-null   float64
 28  Terrace            68146 non-null   float64
 29  ToiletCount        96166 non-null   float64
 30  TypeOfProperty     118399 non-null  int64
 31  TypeOfSale         118399 non-null  float64
dtypes: float64(16), int64(5), object(11)
memory usage: 29.8+ MB

In [11]:
print(df["StateOfBuilding"].unique())
print(df["PEB"].unique())

['GOOD' 'TO_BE_DONE_UP' 'AS_NEW' None 'TO_RENOVATE' 'TO_RESTORE'
 'JUST_RENOVATED']
[None 'D' 'B' 'F' 'E' 'C' 'A' 'G' 'A++' 'A+' 'B_A' 'A_A+' 'E_D' 'E_C'
 'F_C' 'F_D' 'G_F' 'G_C' 'F_E']

In [19]:
x=df[df["TypeOfSale"]==1].groupby(by="PEB").Price.mean().index.values.tolist()
x.reverse()

In [71]:
state_scaler= [None,"TO_BE_DONE_UP","TO_RESTORE","TO_RENOVATE","GOOD","JUST_RENOVATED","AS_NEW"]
peb_scaler=[None,'G_F',
 'G_C',
 'G',
 'F_E',
 'F_D',
 'F_C',
 'F',
 'E_D',
 'E_C',
 'E',
 'D',
 'C',
 'B_A',
 'B',
 'A'
 'A_A+',
 'A+'
 'A++',
 ]

In [58]:
target=["Price"]
int_cols=["TypeOfProperty","TypeOfSale","BedroomCount","BathroomCount","ConstructionYear"]
bool_cols=["Garden","Terrace","SwimmingPool"]
float_cols=["LivingArea","GardenArea"]
ordinal=["StateOfBuilding","PEB"]
categorical=["SubtypeOfProperty","Kitchen","Province"]

columns_to_keep=target+int_cols+bool_cols+float_cols+ordinal+categorical
len(columns_to_keep)

16

In [74]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline

ct_int_cols=ColumnTransformer(("int_imput",SimpleImputer(strategy="most_frequent",copy=False)),remainder="passthrough")
ct_float_cols=ColumnTransformer(("imput_float",SimpleImputer(strategy="mean",copy=False)))
ct_categorical=ColumnTransformer(("cat_encoder",OneHotEncoder(handle_unknown="ignore")))

preprocessor=ColumnTransformer( transformers=
    [
        ("bool_col",SimpleImputer(strategy="constant",fill_value=0.0),bool_cols),
        ("int_col",SimpleImputer(strategy="most_frequent"),int_cols),
        ("float_cols",SimpleImputer(strategy="mean"),float_cols),
        ("ordinal_cols",OrdinalEncoder(categories=[state_scaler,peb_scaler],handle_unknown="use_encoded_value",unknown_value=-1),ordinal),
        ("categorical_col",OneHotEncoder(sparse_output=False),categorical)
    ],
    remainder="passthrough"
)
X=preprocessor.fit_transform(df[columns_to_keep])
df_preprocessed=pd.DataFrame(X,columns=preprocessor.get_feature_names_out())
df_preprocessed.head()

,bool_col__Garden,bool_col__Terrace,bool_col__SwimmingPool,int_col__TypeOfProperty,int_col__TypeOfSale,int_col__BedroomCount,int_col__BathroomCount,int_col__ConstructionYear,float_cols__LivingArea,float_cols__GardenArea,...,categorical_col__Province_Flemish Brabant,categorical_col__Province_Hainaut,categorical_col__Province_Limburg,categorical_col__Province_Liège,categorical_col__Province_Luxembourg,categorical_col__Province_Namur,categorical_col__Province_Walloon Brabant,categorical_col__Province_West Flanders,categorical_col__Province_None,remainder__Price
0,0.0,1.0,0.0,2.0,1.0,1.0,1.0,1969.0,29.000000,45232.714553,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,99000.0
1,0.0,0.0,0.0,1.0,1.0,13.0,6.0,1920.0,391.000000,45232.714553,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,765000.0
2,0.0,0.0,0.0,1.0,1.0,4.0,2.0,2008.0,111.000000,45232.714553,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,399000.0
3,1.0,1.0,0.0,1.0,1.0,4.0,1.0,2024.0,167.437801,1.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,230000.0
4,0.0,1.0,0.0,2.0,1.0,2.0,0.0,1972.0,92.000000,45232.714553,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,198000.0

In [87]:
preprocessor.feature_names_in_

array(['Price', 'TypeOfProperty', 'TypeOfSale', 'BedroomCount',
       'BathroomCount', 'ConstructionYear', 'Garden', 'Terrace',
       'SwimmingPool', 'LivingArea', 'GardenArea', 'StateOfBuilding',
       'PEB', 'SubtypeOfProperty', 'Kitchen', 'Province'], dtype=object)

In [79]:
#Save Preprocessor
import pickle
pickle.dump(preprocessor,open("../data/preprocessor.pkl","wb"))

In [83]:
y=df_preprocessed["remainder__Price"]
X=df_preprocessed.drop(["remainder__Price"],axis=1)

In [84]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1,random_state=42)
print(X_train.shape,X_test.shape)

(106559, 57) (11840, 57)

In [85]:
from sklearn.ensemble import RandomForestRegressor
model=RandomForestRegressor()
model.fit(X_train,y_train)

RandomForestRegressor()

In [86]:
from sklearn.metrics import mean_absolute_error
score=mean_absolute_error(y_true=y_test,y_pred=model.predict(X_test))
print(score)

86830.76088820904

In [7]:
df.TypeOfSale.unique()

array(['residential_sale', 'residential_monthly_rent',
       'annuity_without_lump_sum', 'annuity_monthly_amount',
       'homes_to_build', 'annuity_lump_sum'], dtype=object)

In [ ]:
from sklearn.